#ifndef SRC_TRACKER_ALGORITHMS_LOCAL_PROBABILISTIC_ALGORITHM_LOCAL_PROBABILISTIC_DEFAULTS_H_
#define SRC_TRACKER_ALGORITHMS_LOCAL_PROBABILISTIC_ALGORITHM_LOCAL_PROBABILISTIC_DEFAULTS_H_

#define DEFAULT_LOCAL_PROBABILISTIC_STEPSIZE_IN_PIXELDIM                         0.1
#define DEFAULT_LOCAL_PROBABILISTIC_MINRADIUSOFCURVATURE_IN_PIXELDIM             0.5
#define DEFAULT_LOCAL_PROBABILISTIC_MINFODAMP                                  0.025
#define DEFAULT_LOCAL_PROBABILISTIC_MINLENGTH                                  1e-10
#define DEFAULT_LOCAL_PROBABILISTIC_MAXLENGTH                                  1e+10
#define DEFAULT_LOCAL_PROBABILISTIC_WRITEINTERVAL_IN_PIXELDIM                    0.5
#define DEFAULT_LOCAL_PROBABILISTIC_TRIESPERREJECTIONSAMPLING                  10000

#define DEFAULT_LOCAL_PROBABILISTIC_INIT_POSTESTITCOUNT_INITIAL_CONDITION 		  50
#define DEFAULT_LOCAL_PROBABILISTIC_PROP_POSTESTITCOUNT_INITIAL_CONDITION 		  20
#define DEFAULT_LOCAL_PROBABILISTIC_MAXPOSTESTITINIT 			                1000
#define DEFAULT_LOCAL_PROBABILISTIC_MINPOSTESTITINIT 	 		                   1
#define DEFAULT_LOCAL_PROBABILISTIC_MAXPOSTESTIT 				                1000
#define DEFAULT_LOCAL_PROBABILISTIC_MINPOSTESTIT 		 		                   1
#define DEFAULT_LOCAL_PROBABILISTIC_MAXPOSTESTCOMPENS 	  		                   2 // 100% compensation for underestimation

#endif
