#ifndef SRC_TRACKER_ALGORITHMS_PTT_WITH_PARAMETER_PRIORS_DEFAULTS_H_
#define SRC_TRACKER_ALGORITHMS_PTT_WITH_PARAMETER_PRIORS_DEFAULTS_H_

#define DEFAULT_PTT_WITH_PARAMETER_PRIORS_STEPSIZE_IN_PIXELDIM                       0.025
#define DEFAULT_PTT_WITH_PARAMETER_PRIORS_MINRADIUSOFCURVATURE_IN_PIXELDIM             0.5
#define DEFAULT_PTT_WITH_PARAMETER_PRIORS_PROBELENGTH_IN_PIXELDIM                     0.25
#define DEFAULT_PTT_WITH_PARAMETER_PRIORS_PROBERADIUS_IN_PIXELDIM                      0.5
#define DEFAULT_PTT_WITH_PARAMETER_PRIORS_PROBECOUNT                                     1
#define DEFAULT_PTT_WITH_PARAMETER_PRIORS_PROBECOUNT_WHEN_THEREIS_PROBERADIUS            4
#define DEFAULT_PTT_WITH_PARAMETER_PRIORS_PROBEQUALITY                                   4
#define DEFAULT_PTT_WITH_PARAMETER_PRIORS_MINFODAMP                                   0.05
#define DEFAULT_PTT_WITH_PARAMETER_PRIORS_MAXESTINTERVAL                                 1
#define DEFAULT_PTT_WITH_PARAMETER_PRIORS_DATASUPPORTEXPONENT                            1
#define DEFAULT_PTT_WITH_PARAMETER_PRIORS_MINLENGTH                                  1e-10
#define DEFAULT_PTT_WITH_PARAMETER_PRIORS_MAXLENGTH                                  1e+10
#define DEFAULT_PTT_WITH_PARAMETER_PRIORS_WRITEINTERVAL_IN_PIXELDIM                    0.5
#define DEFAULT_PTT_WITH_PARAMETER_PRIORS_TRIESPERREJECTIONSAMPLING                   1000

#define DEFAULT_PTT_WITH_PARAMETER_PRIORS_INIT_POSTESTITCOUNT_INITIAL_CONDITION 	  1000
#define DEFAULT_PTT_WITH_PARAMETER_PRIORS_PROP_POSTESTITCOUNT_INITIAL_CONDITION 		20
#define DEFAULT_PTT_WITH_PARAMETER_PRIORS_MAXPOSTESTCOMPENS 	  		   			     2

#define DEFAULT_PTT_WITH_PARAMETER_PRIORS_INIT_MAXPOSTESTIT 						  1000
#define DEFAULT_PTT_WITH_PARAMETER_PRIORS_INIT_MINPOSTESTIT 	 		   				 1
#define DEFAULT_PTT_WITH_PARAMETER_PRIORS_PROP_MAXPOSTESTIT 						  1000
#define DEFAULT_PTT_WITH_PARAMETER_PRIORS_PROP_MINPOSTESTIT 		 		   			 1

#endif
